// Generated by CoffeeScript 1.6.3
var Potion;

_.templateSettings = {
  interpolate: /\{\{(.+?)\}\}/g
};

Potion = {
  render: function(page, data, controller) {
    if (data == null) {
      data = {};
    }
    return $.get("views/" + page + ".html", function(html) {
      html = _.template(html, data);
      $('body').html(html);
      return controller();
    });
  },
  controller: {
    login: function() {
      $('#password').keyup(function(e) {
        if (e.keyCode === 13) {
          return $('#login').click();
        }
      });
      return $('#login').click(function() {
        var user;
        Potion.github = new Github({
          username: $('#username').val(),
          password: $('#password').val(),
          auth: "basic"
        });
        user = Potion.github.getUser();
        return user.repos(function(err, repos) {
          return Potion.render("choose", repos, Potion.controller.choose);
        });
      });
    },
    choose: function() {}
  },
  init: function() {
    return Potion.render("login", {}, Potion.controller.login);
  }
};

Potion.init();
