// Generated by CoffeeScript 1.6.2
var Potion;

_.templateSettings = {
  interpolate: /\{\{(.+?)\}\}/g
};

Potion = {
  attachEvents: function() {
    $(document).on('click', '.login-submit', function(e) {
      return Potion.render("choose");
    });
    return null;
  },
  render: function(page, data) {
    if (data == null) {
      data = {};
    }
    $.get("views/" + page + ".html", function(html) {
      html = _.template(html, data);
      return $('body').html(html);
    });
    return null;
  },
  init: function() {
    console.log(1);
    Potion.render("login");
    Potion.attachEvents();
    return null;
  }
};

Potion.init();
