// Generated by CoffeeScript 1.6.3
var Potion;

_.templateSettings = {
  interpolate: /\{\{(.+?)\}\}/g
};

Potion = {
  render: function(page, data) {
    if (data == null) {
      data = {};
    }
    return $.get("views/" + page + ".html", function(html) {
      html = _.template(html, data);
      return $('body').html(html);
    });
  },
  init: function() {
    console.log(1);
    return Potion.render("login");
  }
};

Potion.init();
